name: asashishi agent linux ci

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: |
          go mod download
          npm install

      - name: build project
        run: |
          go build -ldflags="-s -w" -trimpath -o asashishi-agent
          npm run build

      - name: run tests
        run: |
          chmod +x ./run-test.sh ./asashishi-agent
          ./run-test.sh
